import { test } from 'node:test';
import assert from 'node:assert/strict';
import { LocalRepository, users } from '../src/services/repository';
import type { ServiceId, ServiceRequest } from '../src/models';
const entry=users[0],ops=users[1],supervisor=users[2];
function setup(){const map=new Map<string,string>();const storage={getItem:(k:string)=>map.get(k)||null,setItem:(k:string,v:string)=>{map.set(k,v)}};const repo=new LocalRepository(storage);const create=(serviceId:ServiceId,details:ServiceRequest['details'])=>repo.create({companyId:'co1',accountId:'ac1',serviceId,details,notes:'اختبار العرض'},entry);const card={companyId:'co1',employeeId:'EMP001',last4:'4321',reference:'TEST-EXTERNAL-001',holder:'محمد أحمد علي',printedName:'MOHAMMED ALI',issuedAt:'2026-09-29',expiresAt:'2029-09-29',status:'Active' as const,delivered:false};return {repo,storage,create,card};}
test('A: employee card issuance persists and links to company, employee and request',()=>{const {repo,storage,create,card}=setup();const id=create('issue',{employeeId:'EMP001',printedName:'MOHAMMED ALI'});assert.equal(repo.snapshot().requests[0].status,'Pending');assert.throws(()=>repo.transition(id,'InProgress',entry));repo.transition(id,'InProgress',ops);assert.throws(()=>repo.transition(id,'Completed',ops));const cardId=repo.addCard(card,ops,id);repo.transition(id,'Completed',ops);const saved=new LocalRepository(storage).snapshot();const issued=saved.cards.find(c=>c.id===cardId)!;assert.equal(issued.employeeId,'EMP001');assert.equal(issued.companyId,'co1');assert.equal(issued.requestId,id);assert.equal(saved.requests.find(r=>r.id===id)?.status,'Completed');assert.equal(saved.requests.find(r=>r.id===id)?.history.length,4);assert.throws(()=>repo.transition(id,'InProgress',ops));});
test('B: manually registered external card available for PIN request',()=>{const {repo,create,card}=setup();const cardId=repo.addCard(card,ops);assert.equal(repo.snapshot().cards.find(c=>c.id===cardId)?.source,'Manual');const id=create('pin',{cardId});repo.transition(id,'InProgress',ops);assert.throws(()=>repo.transition(id,'Completed',ops));repo.saveOperation(id,{externalConfirmed:true},'',ops);repo.transition(id,'Completed',ops);assert.equal(repo.snapshot().requests[0].status,'Completed');});
test('C: replacement preserves old record and links new card',()=>{const {repo,create,card}=setup();const id=create('replace',{cardId:'card1',reason:'فقدان البطاقة'});repo.transition(id,'InProgress',ops);const newId=repo.addCard({...card,employeeId:undefined},ops,id);assert.equal(repo.snapshot().cards.find(c=>c.id==='card1')?.status,'Active');repo.transition(id,'Completed',ops);const db=repo.snapshot();assert.equal(db.cards.find(c=>c.id==='card1')?.status,'Replaced');assert.equal(db.cards.find(c=>c.id===newId)?.replacementForCardId,'card1');assert.ok(create('pin',{cardId:newId}));});
test('D: top-up requires successful external result, reference and date',()=>{const {repo,create}=setup();assert.throws(()=>create('topup',{cardId:'card1',amount:0}));const id=create('topup',{cardId:'card1',amount:1250});repo.transition(id,'InProgress',ops);repo.saveOperation(id,{result:'failed'},'',ops);assert.throws(()=>repo.transition(id,'Completed',ops));repo.saveOperation(id,{result:'success',transactionReference:'TX-2026-001',executionDate:'2026-09-29'},'تم التنفيذ خارجياً',ops);repo.transition(id,'Completed',ops);assert.equal(repo.snapshot().requests[0].details.transactionReference,'TX-2026-001');});
test('E: statement attachment and date range survive reload',()=>{const {repo,storage,create}=setup();assert.throws(()=>create('statement',{cardId:'card1',from:'2026-10-01',to:'2026-09-01'}));const id=create('statement',{cardId:'card1',from:'2026-09-01',to:'2026-09-29'});repo.transition(id,'InProgress',ops);assert.throws(()=>repo.transition(id,'Completed',ops));repo.attach(id,{id:'pdf1',name:'statement.pdf',size:9,uploadedAt:new Date().toISOString(),dataUrl:'data:application/pdf;base64,JVBERi0xLjc='},ops);repo.transition(id,'Completed',ops);assert.equal(new LocalRepository(storage).snapshot().requests[0].attachments[0].name,'statement.pdf');});
test('F: rejection requires reason and records actor/history',()=>{const {repo,create}=setup();const id=create('pin',{cardId:'card1'});assert.throws(()=>repo.transition(id,'Rejected',ops,''));repo.transition(id,'Rejected',ops,'مستندات غير مكتملة');const r=repo.snapshot().requests[0];assert.equal(r.status,'Rejected');assert.equal(r.rejectionReason,'مستندات غير مكتملة');assert.equal(r.history.at(-1)?.actor,ops.name);});
test('Status change is deferred until completion; delivery persists',()=>{const {repo,create}=setup();const id=create('status',{cardId:'card1',requestedStatus:'Suspended',reason:'طلب الشركة'});repo.transition(id,'InProgress',ops);assert.equal(repo.snapshot().cards[0].status,'Active');repo.transition(id,'Completed',ops);assert.equal(repo.snapshot().cards[0].status,'Suspended');const delivery=create('deliver',{cardId:'card2'});repo.transition(delivery,'InProgress',ops);assert.throws(()=>repo.transition(delivery,'Completed',ops));repo.saveOperation(delivery,{recipient:'محمد علي',identity:'DEMO-ID',deliveryDate:'2026-09-29'},'',ops);repo.transition(delivery,'Completed',ops);assert.equal(repo.snapshot().cards.find(c=>c.id==='card2')?.delivered,true);assert.throws(()=>create('deliver',{cardId:'card2'}));});
test('Permissions, company isolation, cancellation and reset',()=>{const {repo,storage,create,card}=setup();assert.throws(()=>repo.addCard(card,entry));assert.throws(()=>create('pin',{cardId:'card4'}));assert.throws(()=>create('issue',{employeeId:'EMP004',printedName:'TEST'}));const id=create('pin',{cardId:'card1'});repo.transition(id,'Cancelled',entry,'طلب الشركة');assert.equal(repo.snapshot().requests[0].status,'Cancelled');assert.throws(()=>repo.reset(entry));repo.setUser('operations');assert.equal(new LocalRepository(storage).user().id,'operations');repo.reset(supervisor);assert.equal(repo.snapshot().requests.length,28);assert.ok(!repo.snapshot().requests.some(r=>r.id===id));assert.equal(new LocalRepository(storage).snapshot().requests.length,28);});
test('Storage failure does not mutate in-memory records',()=>{const repo=new LocalRepository({getItem:()=>null,setItem:()=>{throw Error('quota')}});const count=repo.snapshot().requests.length;assert.throws(()=>repo.create({companyId:'co1',accountId:'ac1',serviceId:'pin',details:{cardId:'card1'},notes:''},entry));assert.equal(repo.snapshot().requests.length,count);});
