import { Link } from 'react-router-dom';
import { Plus, ArrowLeft, FileText, Clock3, LoaderCircle, CircleCheck, CircleX, CreditCard, Building2, ArrowUpLeft } from 'lucide-react';
import { Heading, Panel, RequestTable, useApp, date } from '../components/ui';
import { today } from '../services/repository';
export default function Dashboard(){const {db,user}=useApp();const pending=db.requests.filter(r=>r.status==='Pending');const completed=db.requests.filter(r=>r.status==='Completed').length;const stats=[{label:'طلبات اليوم',value:db.requests.filter(r=>r.createdAt.slice(0,10)===today()).length,icon:FileText,color:'green',hint:'طلبات مسجلة اليوم',path:'/requests'},{label:'قيد الانتظار',value:pending.length,icon:Clock3,color:'amber',hint:'بانتظار بدء المعالجة',path:'/requests?status=Pending'},{label:'قيد التنفيذ',value:db.requests.filter(r=>r.status==='InProgress').length,icon:LoaderCircle,color:'blue',hint:'تجري معالجتها الآن',path:'/requests?status=InProgress'},{label:'مكتملة',value:completed,icon:CircleCheck,color:'green',hint:'تم إنجاز الخدمة',path:'/requests?status=Completed'},{label:'مرفوضة',value:db.requests.filter(r=>r.status==='Rejected').length,icon:CircleX,color:'red',hint:'تحتاج إلى مراجعة',path:'/requests?status=Rejected'}];const activity=db.requests.flatMap(r=>r.history.map(h=>({...h,requestId:r.id}))).sort((a,b)=>b.at.localeCompare(a.at)).slice(0,4);return <>
 <Heading title="نظرة عامة" subtitle="كل ما تحتاجه لمتابعة طلبات الشركات، في مكان واحد.">{user.permissions.includes('create')&&<Link className="button primary" to="/requests/new"><Plus size={18}/>إنشاء طلب جديد</Link>}</Heading>
 <section className="welcome"><div><span className="welcome-label">إدارة خدمات الشركات</span><h2>مرحباً، {user.name.split(' ')[0]} <span className="wave">✦</span></h2><p>لديك <b>{pending.length} طلبات</b> بانتظار المعالجة. لنواصل تقديم خدمة أفضل.</p><Link to="/requests?status=Pending">استعراض الطلبات المعلقة <ArrowLeft size={16}/></Link></div><div className="welcome-art"><div className="mini-card"><CreditCard size={29}/><span>مدار للأعمال</span><b className="latin">•••• &nbsp; •••• &nbsp; 4821</b><small>خدمات مصرفية، بخطوات أوضح</small></div><div className="art-square"/></div></section>
 <div className="stats">{stats.map(s=><Link key={s.label} className="stat" to={s.path}><div className="stat-top"><span>{s.label}</span><span className={`stat-icon ${s.color}`}><s.icon size={20}/></span></div><strong>{s.value.toLocaleString('ar-LY')}</strong><small>{s.hint}</small></Link>)}</div>
 <div className="dashboard-grid"><Panel title="أحدث الطلبات" action={<Link className="text-link" to="/requests">عرض الكل <ArrowLeft size={14}/></Link>} className="recent-table"><RequestTable requests={db.requests.slice(0,6)} compact/></Panel><Panel title="توزيع الطلبات حسب الخدمة"><div className="distribution">{db.services.map((s,i)=>{const n=db.requests.filter(r=>r.serviceId===s.id).length;return <div key={s.id}><div className="bar-label"><span>{s.name}</span><b>{n}</b></div><div className="bar-track"><div style={{width:`${n/Math.max(1,db.requests.length)*100}%`,background:['#207b6d','#469686','#7aae9f','#b4c7b3','#d3b575','#879eab','#677d79'][i]}}/></div></div>})}</div><div className="distribution-footer"><span>إجمالي الطلبات</span><b>{db.requests.length} طلباً</b></div></Panel></div>
 <div className="dashboard-grid"><Panel title="آخر النشاطات" action={<span className="muted">سجل الإجراءات</span>}><div className="activity-list">{activity.map(h=><div className="activity" key={h.id}><span className="activity-dot"><CircleCheck size={17}/></span><div><strong>{h.text}</strong><small>{h.actor} · <Link to={`/requests/${h.requestId}`} className="request-id">{h.requestId}</Link></small></div><time>{date(h.at)}</time></div>)}</div></Panel><Panel title="مساحة خدمات الشركات"><div className="quick-stat"><Building2/><div><b>{db.companies.length} شركات مسجلة</b><small>حسابات وموظفون وبطاقات مترابطة</small></div><Link to="/companies" aria-label="الشركات"><ArrowUpLeft/></Link></div><div className="quick-stat"><CreditCard/><div><b>{db.cards.length} بطاقة مسبقة الدفع</b><small>بطاقات الشركات والموظفين</small></div><Link to="/cards" aria-label="البطاقات"><ArrowUpLeft/></Link></div><p className="note">جميع الأسماء والبيانات في هذه النسخة خيالية ومخصصة للعرض.</p></Panel></div>
 </>}
